### ISSUE TITLE
Login rerouted to Error page.

### ISSUE THREAD

**Issue by Vivalldi** [Diyzzuf/grav-plugin-private#1]
When I login in to private (whole site is private) the redirect goes to the 404 error page.

**Comment by Diyzzuf** [comment]
I haven't been able to reproduce the error. The only 404 I have is when accessing the site from a false url before login.
The login page stores the URL of the referring page before displaying the login page and redirects to that after.
Can you give me more information about your setup? eg. The access address, if it exists, if you have a page "/", other plugins installed..
Thanks

**Comment by Vivalldi** [comment]
@Diyzzuf It does not matter what page I am attempting to reach first. The private plugin then kicks me straight to /error (Grav then fills it with the 404 because it can't find it just like it would be unable to find /tchuck) I am directing my browser to correct url's that have pages that show after login (after manual redirect).

 I just did a fresh install and cache clear and do not have any other plugins installed. I am then able to navigate to correct pages and stay logged in, it just kicks me when it does the redirect after login.

**Comment by Diyzzuf** [comment]
Can you test that ?
on private.yaml, add the home variable on line 6

``` yaml
routes:
  login: "/login"
  logout: "/logout"
  home: "/"
```

on private.php, modify ( line 159 )

``` php
$redirect_referer = $_SESSION['referer_redirect'];
unset($_SESSION['referer_redirect']); 
$this->grav->redirect($redirect_referer);
```

by

``` php
if($options['private_site'] == true ) {
     $redirect_referer = $options['routes']['home'];
}else{
    $redirect_referer = $_SESSION['referer_redirect'];
    unset($_SESSION['referer_redirect']); 
}
$this->grav->redirect($redirect_referer);
```

I've added the 'home' var, for the redirection after login for full private site. Make your home path ( or another path you want to redirect ), a test. If it's ok, i update the plugin.

**Comment by Vivalldi** [comment]
That does fix it.  The home variable works great (I can set it to any page).

**Comment by Diyzzuf** [comment]
? Closed = Fixed ?

**Comment by Vivalldi** [comment]
yeah. I used your patch and it worked fine.

**Comment by Diyzzuf** [comment]
Thanks for the report ;)
I've seen another bug. I update the plugin for both and release that.
Thanks
