### ISSUE TITLE
Plugin Conflictions

### ISSUE THREAD

**Issue by Vivalldi** [Diyzzuf/grav-plugin-private#10]
Hello Diyzzuf!
I am working with grav at the moment and we have just recently released our admin plugin (with a login plugin). Many users still enjoy your plugin and we need some help in order for your plugin to be continued to be downloaded. If you could create a "develop" branch of your "grav-plugin-priavte" repository it would be wonderful. The "develop" branch is the branch that the general majority of plugins are stable at so we pull from that. Even if you make your "develop" branch the same as you "master" branch it would be a great help allowing users to download and update your plugin from the admin panel.
Thank you!

**Comment by Diyzzuf** [comment]
Sorry, no good internet connection this last year, and with the progress of Admin plugin ( and I work with a personal CMS now ), I've somewhat neglected my plugin ^^
I've opened the develop branch.
When the admin plugin release on stable and paid version, my plugin will be deleted. ( Conflict with paid features )
