### ISSUE TITLE
Hide Hidden Tag

### ISSUE THREAD

**Issue by ghost** [Diyzzuf/grav-plugin-private#16]
Is there a way to hide the "Hidden" tag? ... or am I missing something?

See attachment ...

![capture](https://cloud.githubusercontent.com/assets/5008228/15135895/403f2f80-1641-11e6-86cc-0cef017144ea.PNG)

**Comment by Diyzzuf** [comment]
Fast version : 

You can add a condition when list is display, like

```
        {% if tax != 'hidden' %}
            <a class="{{ active }}" href="{{ base_url }}/{{ taxonomy }}{{ config.system.param_sep }}{{ tax }}">{{ tax }}</a>
        {% endif %}

```

Where 'hidden' is the tag you have defined on private plugin config.

If you use the Taxonomylist plugin, the `taxonomylist/partials/taxonomylist.html.twig` is

```
{% set taxlist = taxonomylist.get() %}

{% if taxlist %}
<span class="tags">
    {% for tax,value in taxlist[taxonomy] %}
        {% set active = uri.param(taxonomy) == tax ? 'active' : '' %}
        {% if tax != 'hidden' %}
            <a class="{{ active }}" href="{{ base_url }}/{{ taxonomy }}{{ config.system.param_sep }}{{ tax }}">{{ tax }}</a>
        {% endif %}
    {% endfor %}
</span>
{% endif %}
```

**Comment by ghost** [comment]
Is there a better way than customizing the plugin? The first time plugin gets updated, any and all customizations are gone.

It seems like a better way to privatize a page would be to simply add something to the twig header of that page.

**Comment by Diyzzuf** [comment]
No way, just put your hands on the code, sorry.
They are no future release/enhancement because it's a future option for the **Premium Admin Plugin**.
