### ISSUE TITLE
Suggestion, make multiple user to be able to open several DIFFERENT kind of pages.

### ISSUE THREAD

**Issue by notalentgeek** [Diyzzuf/grav-plugin-private#19]
Here is what I propose.
Let say I have these user in my `private.yaml`.
- no_user: _password_
- admin1: _password_
- admin2: _password_
- user1 _password_
- user2  _password_

I want so that admin1 only can open some pages while other user can only open some other different pages.

I would love to fork, but I do not have any experience in .php. Perhaps, if you can give me small pointer on which files and lines are important to take note on to, so that I can make this happen.

**Comment by Diyzzuf** [comment]
It's an ACL addons, but sorry, no new release/improve for this plugin.
Because it's a futur feature of the PRO admin plugin, ACL and Private.

**Comment by notalentgeek** [comment]
Would you share a detail on the estimated time and price? I would not mind to pay for the pro version if it does the job.

**Comment by Diyzzuf** [comment]
Sorry, no idea, i'm not on the Grav Staff.
