### ISSUE TITLE
Prevent duplicate sessions. 

### ISSUE THREAD

**Issue by Vivalldi** [Diyzzuf/grav-plugin-private#2]
Other plugins may utilize php sessions. To prevent an error from another session already running I would either name the session or change the `session_start()` to `if (!isset($_SESSION)) { session_start(); }`

**Comment by Diyzzuf** [comment]
Thanks for report !
I change that with new release ;) ( this night )

**Comment by Vivalldi** [comment]
Yep! I was gonna try to figure out how to add tags so that it wouldn't show up as an issue per say but couldn't...

**Comment by Diyzzuf** [comment]
Yep, it's my bug i've referenced this morning. It's correct on the next  
release ;) Don't make the hidden tag on first position for the moment :)

**Comment by Vivalldi** [comment]
Ohh the tags is an issue? Hahaha! I was talking about tagging on github. But thanks for the heads up.

**Comment by Diyzzuf** [comment]
Oops ^^ Sorry, i've a bad english ^^
