### ISSUE TITLE
Default password

### ISSUE THREAD

**Issue by carmelyne** [Diyzzuf/grav-plugin-private#20]
v1.0.2 The default password does not seem to work. Adding new users with (sha1) password does not work either.

**Comment by agentjk** [comment]
v1.0.2 Same here, i use the skeleton-onepage-site and i am not able to get this plugin runnig correct.

**Comment by Diyzzuf** [comment]
I don't understund. I've tried and re-tried, and it works... Default password is `password`.. Changing session_ss doesn't affect the password.. 
Tried with skeleton, last version of Grav... And it works..
Can you send me the php version, and the private.yaml ?

**Comment by agentjk** [comment]
hi,

thnx for your fast response.
looks like i had a prob with the grav version, so i killed everything and start from zero...and now PRIVATE is runnig perfect :)
bye the way thnx for this plugin and sorry for this false alarm
