### ISSUE TITLE
rate limiting login attempts

### ISSUE THREAD

**Issue by dm9876** [Diyzzuf/grav-plugin-private#22]
Hi, with the simple use case of no username and fixed password it can seem like an easy target for brute force. It would be a great enhancement to rate limit logins. Some simple scheme would be sufficient. eg > 20 failed login attempts in any 60 minute period respond with 401. Just make it global, not per user. / session / ip or anything tricky (which is all able to be bypassed anyway)

**Comment by Diyzzuf** [comment]
No enhancement, and not maintained, sorry :/ ( pro version of grav as the same feature [ in the future ] )

**Comment by flaviocopes** [comment]
@Diyzzuf FYI there is no "pro" version of Grav coming in the future, but rather Admin Pro, which will have some additional functionality, but nothing that will step into what your plugin does. So it's still very useful for some people that just want to password-protect the site, without having a user login (something the Login plugin does), but just a simple global password  👍

**Comment by flaviocopes** [comment]
(I commented as I saw some issues closed for this reason)

**Comment by Diyzzuf** [comment]
#17 last post

**Comment by Diyzzuf** [comment]
Beta tester of new release ? ( not on prod )
https://github.com/Diyzzuf/grav-plugin-private-site

Requires Login, Form, Email plugins, and integrated with Admin plugin, on Page=>Options.

Adding and Managing user : https://learn.getgrav.org/admin-panel/faq#adding-and-managing-users
ACL : https://learn.getgrav.org/advanced/groups-and-permissions
Allow User Registration : https://github.com/getgrav/grav-plugin-login/blob/develop/README.md#allow-user-registration
