### ISSUE TITLE
going back after login takes me to wrong page

### ISSUE THREAD

**Issue by ohnonot** [Diyzzuf/grav-plugin-private#23]
i have only a few pages marked hidden, not the whole site.
if i login on those pages, i get taken to the page as expected.
when i then go back (press back button in browser), it takes me to the `/blog` page instead of where i started from.
i have system.yaml set to hide the /blog route in urls.

this happens only after login, once the login session is active going back works normally.

i can always reproduce this by deleting the cookies.

**Comment by ngstigator** [comment]
@ohnonot when i login on any password protected page, i get redirected to /home. is there a configuration i'm missing to go the the page i requested prior to logging in?

**Comment by milojennings** [comment]
When I have `private_site` set to `true` to make privacy site-wide, I am always redirected to `/home` after logging in. It never keeps my place, and it's quite frustrating. Is there a fix for this?

**Comment by Diyzzuf** [comment]
on private.php, line 131, change to
```
else if($this->privateconf['private_site'] == true ) {
    $_SESSION['referer_redirect'] = $this->uri->path(); // new line
    $this->grav->redirect($this->privateconf['routes']['login']);
    return;
}
```

and on the same file, line 172, change to
```

if($this->privateconf['private_site'] == true ) {
    // $redirect_referer = $this->homepath;
    $redirect_referer = $_SESSION['referer_redirect']; //changed line
    unset($_SESSION['referer_redirect']); // new line
}else{
```

I've not tested this code, but normally, it work's.

( you can test the new version of this plugin on https://github.com/Diyzzuf/grav-plugin-private-site )
