### ISSUE TITLE
Post error

### ISSUE THREAD

**Issue by IFLA-MIT** [Diyzzuf/grav-plugin-private#25]
I installed the plugin today (2017-04-21) and set it exactly as your readme.md on GitHub says, but when I try it out and enter the (still default) password, I receive n error:  "Call to a member function post() on null"

Does anyone know why this happens and how I can solve it?

**Comment by Diyzzuf** [comment]
Not Maintained ( because pro version of grav )
But.?? What is your version of grav ? i can't reproduce this on the later version.
And... Any other info/trace for this error ?

**Comment by jeremitu** [comment]
Had the same problem. This seems to be an issue with Form plugin v2.4.0, corrected in current [development version](https://github.com/getgrav/grav-plugin-form) "Extra check for $this->form". Just download the current ZIP and unpack over user/plugin/form until next proper release.

**Comment by Diyzzuf** [comment]
Thanks @jeremitu

**Comment by IFLA-MIT** [comment]
That solution worked just fine for me too.  Thank you @jeremitu!
And thank you both for your time.
