### ISSUE TITLE
Not clear how to make a private page

### ISSUE THREAD

**Issue by roorco** [Diyzzuf/grav-plugin-private#26]
Hi, thanks for your plugin.
 I'm having issues in making a page private.
I have followed the README instruction: turning `private_site: false` in user/config/plugins/private.yaml, adding `private_tag` taxonomy in user/config/site.yaml and adding `private_tag: true` in page taxonomy I want private. 
This is not working for me. Am I doing something wrong?

**Comment by Diyzzuf** [comment]
Yes, it's `private_tag: hidden`.

**Comment by roorco** [comment]
done, no working either. My admin page is showing `Private_tag: hidden` for the page so I suppose my operations were correct. What can I check?

**Comment by Diyzzuf** [comment]
I have not used Grav for a long time, but it seems that you have to write just `tag:hidden` on your page.
like :
```
---
title: 'test 2'
taxonomy:
    tag:  hidden
---
```

I do not remember very well of the use of Grav and Private plugin, but maybe an update as corrupted the function ?
An update of my plugin coming in few week

**Comment by roorco** [comment]
Copying my frontmatter:
```
---
title: 'test'
taxonomy:
    tag:
        - publish
        - research
    private_tag:
        - hidden
---
```

**Comment by Diyzzuf** [comment]
Yep, `hidden` should be on tag list, like

```
---
title: 'test'
taxonomy:
    tag:
        - publish
        - research
        - hidden
---
```

**Comment by roorco** [comment]
Still no luck yet.
Pasting here my user/config/plugins/private.yaml, myabe I'm missing something here:

```
enabled: true

routes:
  login: "/login"
  logout: "/logout"

# MUST BE AN ALPHANUMERIC CHAR
# Generator : http://www.sethcardoza.com/tools/random-password-generator/
session_ss: random_value


private_site: false
private_tag: hidden
enable_username: false

users:
  no_user : 5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8 # By default, is password

texts:
  h1 : Private Area
  h2 : Please <strong>login</strong> to view this content...
fields:
  username:
    label: "Username"
    placeholder: "Enter your username"
  password:
    label: "Password"
    placeholder: "Enter your password"
  antispam:
    label: "Antispam"
    placeholder: "Please leave this field empty for Antispam"
  login:
    label: "Login"
messages:
  success: "You are logged."
  error: "Oops! There was a problem with your submission. Please try again or <a href='https://github.com/Diyzzuf/grav-plugin-private/issues' target='_blank'>report an issue </a>"
  fail: "Oops! Something went wrong.. Try Again !"
```
or having a wrong configuration of private_tag in user/config/site.yaml:
```
title: test
author:
  name: user
  taxonomies: [category, tag, author]
private_tag: hidden
```
Before I was having private_tag inside inside taxonomies brackets. Now I moved below but stil not working.

**Comment by Diyzzuf** [comment]
`private_tag: hidden` is useless on user/config/site.yaml

Just add `hidden` on the `tag` field - or if you haven't the admin plugin, add hidden on tag list

**Comment by roorco** [comment]
ok, but not working, sorry.

**Comment by Diyzzuf** [comment]
Can you post me your page ?

**Comment by roorco** [comment]
I solved the problem with @Diyzzuf, in fact the sesion of private plugin was still on preventing me to change configurations.
So I needed to address to mysite/logout, and after that the plugin worked as expected.
