### ISSUE TITLE
Advice on password hash generation

### ISSUE THREAD

**Issue by uldics** [Diyzzuf/grav-plugin-private#31]
The external site for hash generation should only be advised as a fast checking, not something to be used for anything live (production). Transmitting your password to an unknown site over http is double not secure. Please add to the readme, help or comment in the file, as primary option for hash generation a locally executed command: `echo -n "yourpassword" | sha1sum` instead.

**Comment by karfau** [comment]
Thank you for your contribution.

(_In case feel capable of editing markdown: Did you know you can "directly edit" the [`README.md`](https://github.com/Diyzzuf/grav-plugin-private/blob/master/README.md) file in your browser without leaving github, and it creates a (fork, branch and) PR for you?
Look for the little pencil symbol on top of the file that I linked._)

Best Christian

**Comment by uldics** [comment]
OK, thanks for advice :) Did not know, have done that now. Just not sure about this plugins future - looks like login now manages access for admin and site pages as well.

**Comment by Diyzzuf** [comment]
Thanks.

The future of this plugin is : https://github.com/Diyzzuf/grav-plugin-private-site (beta version, not released. Need users to test this version )
