### ISSUE TITLE
dont works for specific pages

### ISSUE THREAD

**Issue by cesarmarinhorj** [Diyzzuf/grav-plugin-private#33]
when enabled in all site, it works, but, when is false, and enabled in one page, dont.

my page is a blog inside a modular

write this in expert mode
 #taxonomy:
    private_tag: hidden

thanks!

**Comment by Diyzzuf** [comment]
on your config file, `private_tag` is set to `hidden`.
So, on your page, use `hidden` for tag, not `private_tag`

```
---
title: 'A Private Blog Post'
tag: [hidden, yourtaglist]
---
```
