### ISSUE TITLE
Please add grav admin options

### ISSUE THREAD

**Issue by muuvmuuv** [Diyzzuf/grav-plugin-private#35]
It seems your plugin works great so far but does not include integration to grav admin to easier configure your plugins options. Please add this.

**Comment by Diyzzuf** [comment]
https://github.com/Diyzzuf/grav-plugin-private-site   new version...

**Comment by muuvmuuv** [comment]
@Diyzzuf any plans for the release?

**Comment by Diyzzuf** [comment]
It's beta because i wait users reports, but it is functional and can be used on a production.

**Comment by muuvmuuv** [comment]
@Diyzzuf I'll go and test it. Will report any issues to the issue page there and for improvements as well. Thanks!
