### ISSUE TITLE
Nothing happens when editing private.yaml

### ISSUE THREAD

**Issue by kristofferssonida** [Diyzzuf/grav-plugin-private#36]
The private plugin is not working the way I want it to. Even if I update `private_site: false`, the whole page is still password-protected, and nothing changes when I use the hidden-tag on the specific page I want to make private.

Is this some kind of bug or am I doing something wrong?

**Comment by andrekutianski** [comment]
It's similar to my problem. When I set `private_site: false` all pages turn public, but the problem occurs if I try to protect individual pages. I tried different interpretations of the `private_tag` but nothing work.

I using Grav v1.5.7 - Admin v1.8.16

**Comment by andrekutianski** [comment]
@kristofferssonida I have searched on closed issues and have found this question https://github.com/Diyzzuf/grav-plugin-private/issues/26#issuecomment-304043293 the resolution. Add on your 'tag' taxonomy the tag `hidden`. I have test and works.

**Comment by Diyzzuf** [comment]
Sorry, havn't noticed. Thanks @andrekutianski  for help.
