### ISSUE TITLE
Site search returns results from protected pages

### ISSUE THREAD

**Issue by gab-cass** [Diyzzuf/grav-plugin-private#37]
Hi,

I have just installed and configured the plugin, and it works fine. However I have noticed that when doing a site search, results from protected pages are also returned, along with complete public access to those results. 

Use case: 
- I apply protection for a page or chapter
- If I navigate to the page, I am getting prompted for password (desired behavior)
- If I search for a keyword within the protected area, I am getting results and access to the protected area (undesired behavior)

Maybe I am missing something, but this should not happen. Any way to prevent protected content/pages from appearing in search results? I am using the Learn2 theme Thanks.

**Comment by Diyzzuf** [comment]
Thanks for return. I've never noticed for this.
But... this plugin is not maintained.. no futur release.

A new version of this plugin is available : [Private site](https://github.com/Diyzzuf/grav-plugin-private-site). Maybe this plugin solve your bug

**Comment by gab-cass** [comment]
Great, thanks - will look at that one!
