### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by ryanwake01** [Diyzzuf/grav-plugin-private#4]
When changing the default password, how is this done? Do you just add password: newpassword to user>config>plugins>private.yaml  ?  I have added that line to the yaml and it does not seem to affect anything.

**Comment by Diyzzuf** [comment]
Oh sorry, i've forgot this on the Readme. Same as the security salt, it's converted on sha1. Go to a converter, like sha1-online.com, type your password and change it on the private.yaml
Edit : It's already on the Readme, but I admit that it is misplaced. It's on "Users List". I change that for the next release.

**Comment by ryanwake01** [comment]
So in the YAMP it should be something like
password: 367051cf12570e98cc026f02c8e81ded7155c7e3

On Tue, Mar 31, 2015 at 3:32 AM, Diyzzuf notifications@github.com wrote:

> Oh sorry, i've forgot this on the Readme. Same as the security salt, it's
> converted on sha1. Go to a converter, like sha1-online.com, type your
> password and change it on the private.yaml
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Diyzzuf/grav-plugin-private/issues/4#issuecomment-87994519
> .

## 

Ryan Wake
219-226-8898

**Comment by Diyzzuf** [comment]
No, in your yamp, you should have

```
users:
    yourusername : your_sha1_password
```

ex : 

```
users
    ryanwake01 : 367051cf12570e98cc026f02c8e81ded7155c7e3
```

**Comment by ryanwake01** [comment]
Got it, Everything is working beautifully. Thank you sir!  Your help was awesome. 

http://offshorepowerboatgp.com/login

**Comment by bfiedler** [comment]
Please add a comment in private.yaml that directs users to http://www.sha1-online.com/
