### ISSUE TITLE
Hide menu from doc template

### ISSUE THREAD

**Issue by errogaht** [Diyzzuf/grav-plugin-private#8]
Hi! im used Grav documentation template ( http://learn.getgrav.org/ )
your plugin work, but unauthorized user has see left menu, how i can hide it before login?

**Comment by Diyzzuf** [comment]
It's possible with grav version >= 0.9.30. It will hack the original theme, adding 2 lines of codes that I will provide you. But for now the plugin is outdated. I'm on holiday and I will need some days to update my plugin (3-4 days). Thanks for using my plugin :)

**Comment by errogaht** [comment]
It will be great if you add this enhancement, thank you for this plugin, it's
wery useful!

On вт, Июл 14, 2015 at 11:42 PM, Diyzzuf < notifications@github.com [notifications@github.com] > wrote:
It's possible with grav version >= 0.9.30. It will hack the original theme,
adding 2 lines of codes that I will provide you. But for now the plugin is
outdated. I'm on holiday and I will need some days to update my plugin (3-4
days). Thanks for using my plugin :)

—
Reply to this email directly or view it on GitHub
[https://github.com/Diyzzuf/grav-plugin-private/issues/8#issuecomment-121378597] .[https://github.com/notifications/beacon/AGCAKXapcIvOkvjdsb4pCsS7-ZsdCew8ks5odWukgaJpZM4FXed_.gif]

**Comment by Diyzzuf** [comment]
For now, if you want a temporary method, you can override `login.html.twig` file. ( `yoursite/user/plugins/private/templates/login.html.twig` ).

For your theme (rtfm template?), you can write ( if you don't want any sidebar )

``` twig
{% extends 'partials/base.html.twig' %}

{% block sidebar %}
{% endblock %}

{% block content %}
[... Rest of code ...]
```

or ( if you want just logo + search bar )

``` twig
{% extends 'partials/base.html.twig' %}

{% block sidebar %}
    <nav id="sidebar">
        <div id="header">
            <a id="logo" href="{{ theme_config.home_url ?: base_url_absolute }}">{% include 'partials/logo.html.twig' %}</a>
            <div class="searchbox">
                <label for="search-by"><i class="fa fa-search"></i></label>
                <input id="search-by" type="text" placeholder="Search Documentation" data-search-input="{{ base_url_relative }}/search.json/query" />
                <span data-search-clear><i class="fa fa-close"></i></span>
            </div>
        </div>
        <div class="padding">

        </div>
    </nav>
{% endblock %}

{% block content %}
[... Rest of code ...]
```

**Comment by Diyzzuf** [comment]
Finally, it's the best way to hide the menu. I update the plugin soon , but nothing useful about this issues.

**Comment by errogaht** [comment]
Ok, thank you! that's work for me! great...
