### ISSUE TITLE
Conflict with admin plugin and login plugin

### ISSUE THREAD

**Issue by alanski66** [Diyzzuf/grav-plugin-private#9]
The private plugin works great to prevent entry to whole site.
However there is a conflict with the admin/login plugin combination.
Private is using the same template name as the login plugin so private plugin template is never rendered when login plugin is active.
Fix for me was just to rename the template in page.md

**Comment by TribuneX** [comment]
I am getting errors if I try to load the page after rename the login.md in pages to page.md. Can you elaborate on that you changed elsewhere? Thanks!

**Comment by ahmadassaf** [comment]
@TribuneX to resolve this for the moment rename the template in `user/plugins/private/templates` to something like `login-private.html.twig`. 

Then you will need to tell the `login.md` to use that template for rendering. You do this by changing that in the `user/plugins/private/pages/login.md`

```
---
title: Login
slug: login
robots: noindex,nofollow
template: login-private
---
```
